version: "3"
services:
  nodejs:
    image: node:12.16.3
    working_dir: /root/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./app:/root/app
    expose:
      - "8081"
    tty: true